# Generated by Django 6.0.3 on 2026-04-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='maintenance.maintenanceappointment'),
        ),
    ]
